' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml deployment_diagram

package aaa{
    actor Driver

    node "ECU1 (Provider)" as ECU1 {

        boundary "SOME/IP Service Interface" as someip

        control SpeedService

        entity VehicleSpeed

    }

    node "ECU2 (Consumer)" as ECU2 {

        control DisplayService

    }

    Driver --> DisplayService
    DisplayService --> someip
    someip --> SpeedService
    SpeedService --> VehicleSpeed
}

@enduml
