' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml arrows_link

node host_a
node host_b
node host_c
node host_d
node host_e
host_a -- host_b : mark_a
host_a .. host_c : mark_b
host_a ~~ host_d : mark_c
host_a == host_e

artifact bundle_a
artifact bundle_b
artifact bundle_c
artifact bundle_d
artifact bundle_e
artifact bundle_f
artifact bundle_g
artifact bundle_h
artifact bundle_i
artifact bundle_j
bundle_a --> bundle_b
bundle_a --* bundle_c
bundle_a --o bundle_d
bundle_a --+ bundle_e
bundle_a --# bundle_f
bundle_a -->> bundle_g
bundle_a --0 bundle_h
bundle_a --^ bundle_i
bundle_a --(0 bundle_j

@enduml
