# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""
Test suite for dependable_element macro.

Tests the SEooC (Safety Element out of Context) functionality including:
- Index generation with artifact references
- Integration with sphinx_module
- Sphinx-needs cross-referencing
- HTML output generation
"""

load("@bazel_skylib//lib:unittest.bzl", "analysistest", "asserts")
load("@score_tooling//bazel/rules/rules_score:providers.bzl", "SphinxModuleInfo", "SphinxNeedsInfo")

def _seooc_index_generation_test_impl(ctx):
    """Test that dependable_element generates proper index.rst file."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Get the generated index file
    files = target_under_test[DefaultInfo].files.to_list()

    # Find index.rst in the output files
    index_file = None
    for f in files:
        if f.basename == "index.rst":
            index_file = f
            break

    # Assert index file exists
    asserts.true(
        env,
        index_file != None,
        "Expected index.rst to be generated by dependable_element_index rule",
    )

    return analysistest.end(env)

seooc_index_generation_test = analysistest.make(
    impl = _seooc_index_generation_test_impl,
)

def _seooc_artifacts_copied_test_impl(ctx):
    """Test that all dependable element artifacts are copied to output directory."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    files = target_under_test[DefaultInfo].files.to_list()

    # Expected artifact basenames - these come from the SphinxSourcesInfo providers
    # and are filtered to only include .rst/.md files for the index
    expected_artifacts = [
        "feat_req_feat_req_trlc.rst",  # from feature requirements
        "dfa.rst",  # from :dependability_analysis_target
    ]

    # Check each artifact exists
    actual_basenames = [f.basename for f in files]
    for artifact in expected_artifacts:
        asserts.true(
            env,
            artifact in actual_basenames,
            "Expected artifact '{}' to be in output files".format(artifact),
        )

    return analysistest.end(env)

seooc_artifacts_copied_test = analysistest.make(
    impl = _seooc_artifacts_copied_test_impl,
)

def _seooc_sphinx_module_generated_test_impl(ctx):
    """Test that dependable_element generates sphinx_module with HTML output."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Check that SphinxModuleInfo provider exists
    asserts.true(
        env,
        SphinxModuleInfo in target_under_test,
        "Expected dependable_element to provide SphinxModuleInfo from sphinx_module",
    )

    return analysistest.end(env)

seooc_sphinx_module_generated_test = analysistest.make(
    impl = _seooc_sphinx_module_generated_test_impl,
)

def _seooc_needs_provider_test_impl(ctx):
    """Test that dependable_element generates needs provider for cross-referencing."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Check that SphinxNeedsInfo provider exists
    asserts.true(
        env,
        SphinxNeedsInfo in target_under_test,
        "Expected dependable_element_needs to provide SphinxNeedsInfo",
    )

    return analysistest.end(env)

seooc_needs_provider_test = analysistest.make(
    impl = _seooc_needs_provider_test_impl,
)
