' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml nested_elements

artifact item_a {
	card item_b {
		cloud zone_a {
			component part_a {
				database store_a {
					file doc_a {
						folder dir_a {
							frame zone_b {
								hexagon cell_a {
									node host_a {
										package pack_a {
											queue lane_a {
												rectangle box_a {
													stack lane_b {
														storage store_b {
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}

@enduml
