# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Run Python Basics Integration and Unit Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Install Missing Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev
      - name: Run python_basics integration tests
        run: |
          cd python_basics/integration_tests
          bazel test //...
      - name: Run starpls integration tests
        run: |
          cd starpls/integration_tests
          bazel test //...
      - name: Run cr_checker unit tests
        run: |
          cd cr_checker/tests
          bazel test //...
      - name: Run coverage module tests
        run: |
          bazel test //coverage/tests:all
      - name: Run rules_score tests
        run: |
          bazel test //bazel/rules/rules_score/...
      - name: Run Plantuml Tooling clippy
        run: |
          bazel build //plantuml/... --config=clippy
      - name: Run Plantuml Tooling tests
        run: |
          bazel test //plantuml/...
      - name: Run Validation Tooling clippy
        run: |
          bazel build //validation/... --config=clippy
      - name: Run Validation Tooling tests
        run: |
          bazel test //validation/...
      - name: Ensure correct dependency resolution
        run: |
          bazel mod deps --lockfile_mode=update
